# This is a basic workflow to help you get started with Actions

name: gh-pages build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build & Deploy
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with: 
          global: true
          name: 'Anu Shibin'
          email: 'anushibin007@gmail.com'
          token: '${{ secrets.GITHUB_TOKEN }}'
        run: npm run deploy
